FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/server ./cmd/server/main.go

FROM alpine:3.20

RUN adduser -D -H -u 10001 appuser
WORKDIR /app

COPY --from=builder /bin/server /app/server

USER appuser

EXPOSE 8080

ENTRYPOINT ["/app/server"]
